### ISSUE TITLE
Still receive the warning “too many requests”

### ISSUE THREAD

**Issue by Mondmarmelade** [iobroker-community-adapters/ioBroker.spotify-premium#311] opened 2023-12-24 14:59 UTC
I get a "too many requests" warning every 10 seconds.
I thought the bug was fixed in version 1.3.0.

**Screenshots & Logfiles**  
![grafik](https://github.com/iobroker-community-adapters/ioBroker.spotify-premium/assets/91614367/0300a9dc-1799-4fef-9df0-518484f7ee98)

**Versions:**  
 - Adapter version: 1.3.1
 - JS-Controller version: 5.0.16
 - Node version: v18.17.1
 - Operating system: linux (docker)

**Comment by aruttkamp** [comment] 2023-12-28 21:32
Hello Mondmarmelade,
yes, i fixed this. feedback from other users is positive.
please verify version of adapter and please send me your configuration of the adapter. ( Screenshot )

**Comment by aruttkamp** [comment] 2024-01-12 18:49
@Mondmarmelade - please send your configuration.

**Comment by ManiacKill** [comment] 2024-01-15 18:16
Good Morning,

![image](https://github.com/iobroker-community-adapters/ioBroker.spotify-premium/assets/11009572/f1587b8f-2345-4533-be2d-e42942ffde1f)

![image](https://github.com/iobroker-community-adapters/ioBroker.spotify-premium/assets/11009572/c7aec263-3e09-467e-8569-9e984947bd58)

![image](https://github.com/iobroker-community-adapters/ioBroker.spotify-premium/assets/11009572/375772d4-72fd-4e2f-9606-5ed216b8cdc4)

I have the same problem.

**Comment by aruttkamp** [comment] 2024-01-15 19:33
@ManiacKill @Mondmarmelade 
Welche Admin Version setzt Ihr bitte ein  ?

**Comment by aruttkamp** [comment] 2024-01-15 20:32
I can't reproduce the error in my system. 
I am using the adapter in my normal environment and i do some tests in my testsystem just now. 

Can anyone give me an tip how to reproduce this ?

**Comment by c-hum** [comment] 2024-01-15 21:18
Also had this problem and did the following: Deleted all objects in spotify-premium.0.
Afterwards restarted the adapter (objects were generated new) and then I reauthorized through instace settings. 
Since some days the error did not come again. Perhaps worth a try ;-)

**Comment by ManiacKill** [comment] 2024-01-16 03:56
Admin Version 6.12.0

**Comment by n1tr0-5urf3r** [comment] 2024-01-19 20:45
Hi there! I got the same issue. My settings in the Spotify iobroker instance are all set to the recommended ones. 
I am using the jarvis adapter for my visualization. From there I am using the "MediaControl" widget, which links to the spotify premium iobroker adapter. 
I noticed that the "too many requests" log entry only occurs when the visualization is loaded somewhere, e.g., if I open the webpage of jarvis and the Spotify media control is displayed.
I further noticed that the adapter causes a lot of DNS queries during the same period. Approx. 10000 queries to api.spotify.com (A and AAAA).
Probably that helps you in reproducing it. I am using js-controller 5.0.17, admin adapter 6.12.0, spotify adapter 1.3.1 and jarvis 3.1.8

**Comment by aruttkamp** [comment] 2024-01-19 20:50
> Probably that helps you in reproducing it. I am using js-controller 5.0.17, admin adapter 6.12.0, spotify adapter 1.3.1 and jarvis 3.1.8

Yeah. i think that will help. i try to fix it - but it will take a few more days.

**Comment by Technology89** [comment] 2024-02-16 06:22
Hi, any news on that?

**Comment by mcm1957** [comment] 2024-02-24 13:26
@aruttkamp 

Are you still working on this?
Seems to be a problem affecting more than one user:

https://forum.iobroker.net/topic/69146/spotify-too-many-requests/27

**Comment by aruttkamp** [comment] 2024-02-24 19:45
Yes, i am still working on this. last weeks there was no time left beside my job - sorry.

**Comment by n1tr0-5urf3r** [comment] 2024-04-01 10:27
@aruttkamp I tracked the issue down a bit. 

I think the problem is that in your implementation:

1. A request is sent every `statusPollingDelaySeconds` seconds
2. If this request is replied with a http 429 tooManyRequests, you
     a. Check for the retry-after in the reply header
     b. Wait that time and then send a new request

But in this implementation, a new request is sent after `statusPollingDelaySeconds`. This results in another tooManyRequests response and an increased timeout. 

I suggest adding a global flag like `tooManyRequests` that is set when you get a 429 code and reset when the timeout is over. We then need to check for this flag in the `sendRequest` method and only send a request if it is not set. 

I have a possible fix in my development branch: https://github.com/n1tr0-5urf3r/ioBroker.spotify-premium/commit/69bf32fa5f8260a99ec35459e898385cb05be648, but I have not been able to verify it because the problem is not happening for me at the moment. I'll create a PR for a beta if you want.

**Comment by n1tr0-5urf3r** [comment] 2024-04-01 15:13
Update after I've run in the "too many requests" again: The backoff seems to work, meaning that the API is not continuously queried after rate limitting ...
But the main issue why we go into rate limitting is the querying for playlists, more specifically the `getPlaylistTracks` function. I will do some more debugging

**Comment by n1tr0-5urf3r** [comment] 2024-04-09 16:58
After carefully observing the behaviour of my adapter for the past week, I think its fixed now.
The playlist update interval should be increased to a higher value, maybe to ~60 minutes depending on the number of playlists and songs in a playlist. 

For each playlist, an API call is sent for every 50 songs in that playlist. This can result in a lot of API calls at once leading to the 429.
I got some more updates in my PR.

**Comment by mcm1957** [comment] 2024-04-18 07:41
fixed with 1.5.0

**Closed** 2024-04-28 15:32 UTC
Labels: bug, fixed
